### ISSUE TITLE
install instructions don't work for patching chrome-remote-interface

### ISSUE THREAD

**Issue by jason-curtis** [mokev/rofi-switch-browser-tabs#4]
The README instructions for installing with chrome say to:

> `sudo $EDITOR /usr/bin/chrome-remote-interface` and change Line 190 from `console.log(display(tabs))` to `console.log(display(JSON.stringify(tabs)))`

However, [line 190](https://github.com/cyrus-and/chrome-remote-interface/blob/master/bin/client.js#L190) is now a blank line and `display(tabs)` is nowhere to be found in that file.

**Comment by shitikanth** [comment]
FWIW, for me the script works as-is, without a need for any patch.

**Comment by joepio** [comment]
Same for me: the script works fine as is, the `JSON.stringify` is not necessary and could be removed from docs.
